name: pyomo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyomo
  - glpk
  - pip
  - pulp
  - plotly
  - scipy
  - conda-libmamba-solver
  - libarchive
  - pip:
    - streamlit
    - highspy
    
